zotero:
  user_id: ${oc.env:ZOTERO_USER_ID}
  api_key: ${oc.env:ZOTERO_API_KEY}
  include_path: null

email:
  sender: ${oc.env:EMAIL_SENDER}
  receiver: ${oc.env:EMAIL_RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:EMAIL_PASSWORD}

llm:
  api:
    key: "placeholder_key_do_not_delete"
    base_url: "https://generativelanguage.googleapis.com/v1beta"
  generation_kwargs:
    model: "gemini-2.0-flash"
  language: English

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG","eess.IV"]

executor:
  source: ["arxiv"]
