zotero:
  user_id: ${oc.env:ZOTERO_USER_ID}
  api_key: ${oc.env:ZOTERO_API_KEY}
  include_path: null
  ignore_path: null

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG","eess.IV"]
    include_cross_list: false
  biorxiv:
    category: null
  medrxiv:
    category: null

email:
  sender: ${oc.env:EMAIL_SENDER}
  receiver: ${oc.env:EMAIL_RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:EMAIL_PASSWORD}

llm: null

reranker:
  local:
    model: jinaai/jina-embeddings-v5-text-nano-retrieval
    encode_kwargs:
      task: retrieval
      prompt_name: document
  api:
    key: null
    base_url: null
    model: null
    batch_size: null

executor:
  debug: false
  send_empty: false
  max_paper_num: 100
  source: ["arxiv"]
  reranker: local
