zotero:
  user_id: ${oc.env:ZOTERO_USER_ID}
  api_key: ${oc.env:ZOTERO_API_KEY}
  include_path: null

email:
  sender: ${oc.env:EMAIL_SENDER}
  receiver: ${oc.env:EMAIL_RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:EMAIL_PASSWORD}

llm: null

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG","eess.IV"]
    keywords:
      - "Mamba"
      - "Medical Anomaly Detection"
      - "Medical Image Anomaly Detection"
      - "Mamba for medical"
      - "Unsupervised Anomaly Detection"
      - "Medical AI"

executor:
  debug: null
  source: ["arxiv"]
